### ISSUE TITLE
bug: failed to fetch when using LittleSkin

### ISSUE THREAD

**Issue by SerinaNya** [shaokeyibb/mcserver_player_uuid_modifier#1]
## 现象
使用 LittleSkin（外置验证）时未正常工作，提示 **无法拉取远程账户信息**。

用户名实际存在。抓包发现 `POST https://littleskin.cn/api/yggdrasil/api/profiles/minecraft` 返回 HTTP 500。

![image](https://github.com/user-attachments/assets/259e9389-018a-487d-b696-d70598bfe858)

## 原因
LittleSkin 自 2024 年 10 月起启用新的 Yggdrasil API 后端实现，请求头中未带有 `Content-Type: application/json` 将会发生错误。

## 解决方案
发起请求时设置 `Content-Type` 头部。

```rust
#[tauri::command]
pub fn fetch_post(url: &str, body: String) -> Result<String, String> {
    let client = reqwest::blocking::Client::new();
    let res = client
        .post(url)
        .body(body)
        .header("Content-Type", "application/json")
        .send()
        .map_err(|err| err.to_string())?;
    res.text().map_err(|err| err.to_string())
}

```

---

版本 `0.0.3` /  https://github.com/shaokeyibb/mcserver_player_uuid_modifier/commit/761a99a85e836695e38ec75b8f6f510b158acdce

当前代码

https://github.com/shaokeyibb/mcserver_player_uuid_modifier/blob/761a99a85e836695e38ec75b8f6f510b158acdce/src-tauri/src/net.rs#L8-L17

**Comment by shaokeyibb** [comment]
Hi SerinaNya，感谢你告知我这个问题！欢迎你 fork 本项目并提交 PR 来进行修复
